### ISSUE TITLE
Missing 8.0.0 release/tag

### ISSUE THREAD

**Issue by iamrakesh** [wicketstuff/wiquery#2]
Hi,

I am able to see v8.0.0 of wicketstuff/wiquery artifacts in maven repo (at https://mvnrepository.com/artifact/org.wicketstuff.wiquery/wiquery-core); but I am not able to see the release tag in Github at https://github.com/wicketstuff/wiquery/releases
Anything pending for wiquery 8.0.0 release ?

Regards,
Rakesh.A

**Comment by martin-g** [comment]
Thanks for the reminder! 
https://github.com/wicketstuff/wiquery/tree/wiquery-8.0
