### ISSUE TITLE
Alternative for DatePickerLanguageResourceReference

### ISSUE THREAD

**Issue by THISISSUBBU** [wicketstuff/wiquery#3]
HI, 
we are migrating to wicket-8 and switched to wicketstuff wiquery 8.0

I'm getting problem with **DatePickerLanguageResourceReference**, we are using for setting the Locale related ResourceReferences. I observed that DatePickerLanguageResourceReference was removed in wiquery 8.0

> DatePickerLanguageResourceReference.get(aLocale)

What is the alternative way to show locale dependent DatePicker ?

**Comment by florianlacreuse** [comment]
Hi,

We also have the same issue over here, migrating from wicketstuff wiquery 7.0 to 8.0.

We found out through commit d0071d134e5aaeed97f0af870d05a1530b92b53f that `i18n` package and everything inside has been removed.

How are we supposed to deal with locale for datepicker in wiquery 8.0? No migration guide about it was found.

Kind regards.

**Comment by martin-g** [comment]
I have no idea why it has been removed.

Please send a PR that reintroduces the removed functionality!

**Comment by florianlacreuse** [comment]
Thanks for the reply.

I just did a PR about it, see #4.

However, there are several things to check as you can see in conversation page (global comment + review on js files).

**Comment by florianlacreuse** [comment]
@THISISSUBBU You can close this issue. Thanks!
