### ISSUE TITLE
Modularize wiquery or add automatic module name

### ISSUE THREAD

**Issue by theigl** [wicketstuff/wiquery#97]
I'm in the process of modularizing my application and noticed that wiquery currently has neither automatic module name nor module-info:

```
[WARNING] *****************************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [wiquery-core-10.0.0.jar, wiquery-jquery-ui-10.0.0.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] *****************************************************************************************************************************************************************************
```

Should we modularize the project or at least add an automatic module name?

I can provide a PR.

**Comment by martin-g** [comment]
+1 
whatever is easier for you

**Comment by theigl** [comment]
I attempted to modularize the project but the UI module depends on the test-jar of the core module. It is non-trivial to support this setup in a modularized project. Most likely, we would have to introduce a new `wiquery-test` module that both core and UI depend on.

For now, I just went with an automatic module name.
